name: Debian

on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    container: debian:${{ matrix.version }}
    strategy:
      matrix:
        version: ['stable', 'unstable', 'testing']

    steps:
      - uses: actions/checkout@v2

      - name: Install Salt
        run: |
          apt-get -y update
          apt-get -y install curl
          curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
          sh ./bootstrap-salt.sh -X

      # FIXME move this to a testing tool
      - name: Run Tests
        run: |
          salt-call -l debug --local -c .salttest state.show_sls alertlogic.user
          salt-call -l debug --local -c .salttest state.show_sls alertlogic.agent
