name: FreeBSD

on: [pull_request]

jobs:
  Test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        uses: vmactions/freebsd-vm@v0.1.4
        with:
          usesh: true
          prepare: pkg install -y curl
          run: |
            curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
            sh ./bootstrap-salt.sh -X
            salt-call -l debug --local -c .salttest state.show_sls alertlogic.user
            salt-call -l debug --local -c .salttest state.show_sls alertlogic.agent
