name: Windows

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        version: ['2016', '2019']
    runs-on: windows-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Salt
        run: |
          choco install python --version 3.8.0
          Invoke-WebRequest -Uri https://winbootstrap.saltproject.io -OutFile C:\Temp\bootstrap-salt.ps1
          Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser
          C:\Temp\bootstrap-salt.ps1 -X
          Set-ExecutionPolicy -ExecutionPolicy Undefined -Scope CurrentUser

      # FIXME move this to a testing tool
      - name: Run Tests
        run: |
          salt-call -l debug --local -c .salttest state.show_sls alertlogic.user
          salt-call -l debug --local -c .salttest state.show_sls alertlogic.agent
